# Generated by Django 3.2.9 on 2022-07-03 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('year', models.TextField(default='1900')),
                ('img_url', models.TextField(default='')),
                ('movielist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='christmasflix.movielist')),
            ],
        ),
    ]
