# Generated by Django 3.2.7 on 2021-09-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christmasflix', '0002_list_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Movie',
        ),
        migrations.RenameModel(
            old_name='List',
            new_name='Movies',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='list',
            new_name='movies',
        ),
    ]
