# Generated by Django 3.2.7 on 2021-09-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christmasflix', '0003_auto_20210924_2258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='MovieList',
        ),
    ]
