# Generated by Django 3.2.7 on 2021-09-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christmasflix', '0004_rename_movies_movielist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='text',
            new_name='title',
        ),
    ]
