# Generated by Django 3.2.7 on 2021-09-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christmasflix', '0005_rename_text_movie_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movies',
            new_name='movielist',
        ),
    ]
