# Generated by Django 3.2.7 on 2021-10-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmasflix', '0008_auto_20211001_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
