# Generated by Django 3.2.7 on 2021-10-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmasflix', '0009_alter_movielist_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img_url',
            field=models.TextField(default=''),
        ),
    ]
